model: 'MACE'
foundation_model: 'small'
multiheads_finetuning: False
train_file: "/Users/swyant/cesmix/datasets/HfO2_cesmix/april_2025_data_mv/processed_and_split/debug/debug.xyz"
valid_file: "/Users/swyant/cesmix/datasets/HfO2_cesmix/april_2025_data_mv/processed_and_split/debug/debug.xyz"
test_file: "/Users/swyant/cesmix/datasets/HfO2_cesmix/april_2025_data_mv/processed_and_split/debug/debug.xyz"
energy_key: "REF_energy"
forces_key: "REF_forces"
E0s: {8: -443.8224565134432, 72: -1529.4984727695407}
name: "dbg"
model_dir: "."
log_dir: "."
results_dir: "."
#checkpoint_dir: "MACE_models"
device: cpu
batch_size: 1
max_num_epochs: 500
lr: 0.01
swa: True
seed: 123
stress_weight: 0.0
forces_weight: 10.0
energy_weight: 1.0
