
model: 'MACE'
hidden_irreps: '128x0e + 128x1o'
correlation: 3
max_ell: 3
r_max: 6.0
train_file: 'data/nothing_above_5/new_dpp_train.xyz'
valid_file: 'data/nothing_above_5/new_dpp_validation.xyz'
test_file: 'data/nothing_above_5/test.xyz'
energy_key: "REF_energy"
forces_key: "REF_forces"
E0s: {8: -444.4382601985303, 72: -1528.3129784907499}
name: "HfOx_from-scratch"
model_dir: "models/HfOx_from-scratch_1"
log_dir: "models/HfOx_from-scratch_1"
results_dir: "models/HfOx_from-scratch_1"
checkpoints_dir: "models/HfOx_from-scratch_1"
device: cuda
batch_size: 14
max_num_epochs: 1000
lr: 0.01
ema: True
ema_decay: 0.99
optimizer: adam
weight_decay: 5e-7
swa: True
seed: 123
stress_weight: 0.0
forces_weight: 100.0
energy_weight: 1.0
#scheduler_patience: 20
#lr_factor: 0.2
huber_delta: 0.01
wandb: True
enable_cueq: True
wandb_project: "MACE_HfOx_from-scratch"
wandb_name: "HfOx-1"
wandb_log_hypers: ["lr", "lr_factor", "lr_scheduler_gamma", "scheduler",
                   "swa", "swa_lr", "start_swa", "scheduler_patience",
                   "swa_energy_weight", "swa_forces_weight",
                   "energy_weight", "forces_weight",
                   "ema", "ema_decay", "weight_decay",
                   "huber_delta", "optimizer", "amsgrad", "beta",
                   "batch_size", "max_num_epochs", "seed"]

