
model: 'MACE'
foundation_model: 'small'
multiheads_finetuning: False
#train_file: ['data/Hf/trainval', 'data/HfOx/trainval']
#train_file: 'data/HfOx/trainval'
train_file: 'data/HfOx/test/HfOx_amorphous_MC_rattled_form_sorted_test.xyz'
valid_fraction: 0.1
#test_file: ['data/Hf/test', 'data/HfOx/test']
#test_file: 'data/HfOx/test'
test_file: 'data/HfOx/test/HfOx_amorphous_MC_rattled_form_sorted_test.xyz'
energy_key: "REF_energy"
forces_key: "REF_forces"
#E0s: {8: -1529.4984727695407, 72: -443.8224565134432}
E0s: {8: -443.8224565134432, 72: -1529.4984727695407}
#E0s: {8: -1.0, 72: -4.0}
name: "small_ft-HfOx_v0.1"
model_dir: "models/small_HfOx-ft_1"
log_dir: "models/small_HfOx-ft_1"
results_dir: "models/small_HfOx-ft_1"
#checkpoint_dir: "MACE_models"
device: cuda
batch_size: 5
max_num_epochs: 500
lr: 0.01
swa: True
seed: 123
stress_weight: 0.0
forces_weight: 10.0
energy_weight: 1.0
